### PR TITLE
SPI support

### PR DESCRIPTION
**Pull request by rogerdahl**
Hi Richard,

I've added SPI support to your library and have done misc refactoring of the code and docs.

If you'd like me to fix something before pulling, let me know.

If you pull, you'll have to test I2C functionality again. I don't have an I2C display.

Thanks,

Roger

### CODE REVIEW

**Comment by rm-hull** [comment]
Hi, great stuff - I'll check the I2C functionality to make sure it still works ok.

Only comments I have are:
* I have a slight preference for spidev (https://github.com/doceme/py-spidev) for SPI rather than wiringPi2 - that library has a slight kitchen-sink feel to it (in as much as it tries to do everything, rather than just one thing). spidev does support the 3wire interface too.
* Move the import for smbus into the I2C constructor, and the wiringPi2 import into the SPI constructor; This can just replace the sys.modules check/logging and just let the ImportError propagate.
* I seem to vaguely recall that the I2C driver could only transmit max 32 bytes at a time. spidev's xfer2 allows a buffer of something like 4k, so the SPI.data() method should probably not do the chunking. This should result in slightly better performance I suppose.
* Add another section header 'Collaborators' to the readme and add yourself

**Comment by rogerdahl** [comment]
Hi -- glad you like it.

1) I settled on wiringPy because it does both SPI and regular GPIO. I'd be happy to switch to spidev, it certainly looks nice and concise, but I'd still need something like wiringPy for toggling the Data/Command and Reset lines. Suggestions?

2) Done. I'm still catching it so that I can print the hint.

3) Slicing is pretty much free, so I doubt it's worth investigating...

4) Done.

**Comment by rm-hull** [comment]
So we could either go whole hog and use wiringPi2 to do the I2C as well, or use spidev & RPI.GPIO (for reset & D/C) for the SPI

**Comment by rogerdahl** [comment]
Sure, I'll go ahead and convert to spidev & RPI.GPIO. I see that RPI.GPIO plans on adding both I2C and SPI support. If that happens, we can switch to only RPI.GPIO.

**Comment by rogerdahl** [comment]
Oops -- didn't realize that using spidev and RPI.GPIO wouldn't allow us to remove wiringPi2. A refactoring from smbus + wiringPi2 to smbus + spidev + RPI.GPIO doesn't seem to  be worth it. So I think your first suggestion of using wiringPi2 for everything would make the most sense.

**Comment by rogerdahl** [comment]
Took a stab at wiringPi2 for I2C. Untested...

**Comment by rm-hull** [comment]
I'll have a look later on this evening and get it merged. Thanks again!

**Comment by rm-hull** [comment]
Hi, sorry haven't had chance to get to look at this on my RPI yet. Aim to in the next day or so.

**Comment by rm-hull** [comment]
So I had a look at the I2C version, and it doesn't work: It looks like wiringPI can only support sending a single byte at a time, so I changed it to send a single byte at a time here https://github.com/rogerdahl/ssd1306/blob/master/oled/device.py#L58-L59 and here https://github.com/rogerdahl/ssd1306/blob/master/oled/device.py#L67-L70

That still didnt work. 

Looking at wiringPi2, https://github.com/Gadgetoid/WiringPi2-Python/blob/f388d58fbdb5fa308fd69e6b32936e3c76c0481b/WiringPi/wiringPi/wiringPiI2C.c#L165 it seems a bit odd to send data as the command (3rd arg) and null as data (5th arg).

Struggling to find out how python-smbus implements the commands, but on the face of things, seems like wiringPi2 should expose block read & write methods.

**Comment by rogerdahl** [comment]
Yikes, a bytes at a time... Though, apparently, `wiringPiI2CWrite()` has been found to be working at some point:

https://github.com/pasangsherpa/ThermistorReader/blob/master/main.c

To send a block of up to 32 bytes, it looks like one has to fill in a `i2c_smbus_data` but I don't know if WiringPi exposes that.

A couple of the same type of I2C displays you have are on their way from China. If you haven't figured it out by then, I'll be able to do more testing when they arrive.

**Comment by thijstriemstra** [comment]
I guess this can be closed?

**Comment by rm-hull** [comment]
Support for SPI is being reworked under #38

**Pull request closed without merging**
